name: 'Nightly Merge'

on:
  push:
    branches:
      - master
  check_suite:
    type: ['completed']

jobs:
  nightly-merge:
    if: github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'master'
        development_branch: 'staging'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
